name: APK Oluştur

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: APK Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Kodu İndir
      uses: actions/checkout@v3
    
    - name: Java Kur
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Flutter Kur
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Flutter Doctor
      run: flutter doctor -v
    
    - name: Flutter Paketlerini İndir
      run: flutter pub get
    
    - name: Flutter Temizle
      run: flutter clean
    
    - name: Gradle Wrapper İzinlerini Ayarla
      run: chmod +x android/gradlew
    
    - name: Gradle Wrapper Jar İndir
      run: |
        cd android
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar -o gradle/wrapper/gradle-wrapper.jar
        fi
        cd ..
    
    - name: APK Oluştur
      run: flutter build apk --release
    
    - name: APK'yı Yükle
      uses: actions/upload-artifact@v3
      with:
        name: muktar-marangoz-apk
        path: build/app/outputs/flutter-apk/app-release.apk
