name: APK Oluştur

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: APK Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Kodu İndir
      uses: actions/checkout@v3
    
    - name: Java Kur
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Flutter Kur
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Flutter Paketlerini İndir
      run: flutter pub get
    
    - name: APK Oluştur
      run: flutter build apk --release
    
    - name: APK'yı Yükle
      uses: actions/upload-artifact@v3
      with:
        name: muktar-marangoz-apk
        path: build/app/outputs/flutter-apk/app-release.apk
